set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'Lokaltog/vim-powerline'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-scripts/tComment'
Plugin 'kana/vim-fakeclip'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'altercation/vim-colors-solarized'

call vundle#end()

filetype plugin indent on
set shell=/bin/bash\ -i
set autoindent
set nocompatible      " Use vim, no vi defaults
set number            " Show line numbers
set ruler             " Show line and column number
set encoding=utf-8    " Set default encoding to UTF-8
set ttyfast
set title             "show filename in title window
set visualbell
set nobackup          "no backup files
set nowritebackup     "only in case you don't want a backup file while editing
set noswapfile        "no swap files
set ttimeout
set ttimeoutlen=100
set so=7
set foldcolumn=1
set autoread
set showmatch         " Cursor shows matching ) and }
set splitright        " put new buffer on the right of the current buffer

" status line
set laststatus=2
set statusline=%f\ %m\ %r
set statusline+=Line:%l/%L[%p%%]
set statusline+=Col:%v
set statusline+=Buf:#%n

" MAPPINGS
let mapleader="\\"

nmap <leader>n :NERDTreeToggle<CR>
nmap <leader>f :NERDTreeFind<CR>
nnoremap // :TComment<CR>
vnoremap // :TComment<CR>

" find merge conflict markers
nmap <silent> <leader>fc <ESC>/\v^[<=>]{7}( .*\|$)<CR>

" tab selected text
vmap tl <gv
vmap tr >gv
nmap tl <<
nmap tr >>


cnoremap %% <C-R>=expand('%:h').'/'<cr>
cnoremap <C-A> <Home>
cmap w!! w !sudo tee > /dev/null %

set mouse=a

noremap <tab> :tabnext<CR>
noremap <S-tab> :tabprevious<CR>
noremap <leader>w :tabclose<CR>
nmap <leader>D :bd<CR>
map 0 ^


nmap <silent> <leader>h :silent noh<CR>
nmap <leader>l :setlocal number!<CR>
nmap <leader>o :set paste!<CR>
nmap j gj
nmap k gk


" Bubble single lines
nmap J ]e
nmap K [e

" Bubble multiple lines
vmap K [egv
vmap J ]egv

nmap <leader>a :Ag!<space>

" vim-ruby
nmap <C-n> ]m
nmap <C-m> [m

nmap pO O<C-R>"<ESC>
nmap po o<C-R>"<ESC>


""
"" Whitespace
""

set nowrap                        " don't wrap lines
set tabstop=2                     " a tab is two spaces
set shiftwidth=2                  " an autoindent (with <<) is two spaces
set expandtab                     " use spaces, not tabs
set list                          " Show invisible characters
set backspace=indent,eol,start    " backspace through everything in insert mode

" List chars
set listchars=""                  " Reset the listchars
set listchars=tab:\ \             " a tab should display as "  ", trailing whitespace as "."
set listchars+=trail:.            " show trailing spaces as dots
set listchars+=extends:>          " The character to show in the last column when wrap is
                                  " off and the line continues beyond the right of the screen
set listchars+=precedes:<         " The character to show in the last column when wrap is
                                  " off and the line continues

set hlsearch    " highlight matches
set incsearch   " incremental searching
set ignorecase  " searches are case insensitive...
set smartcase   " ... unless they contain at least one capital letter

" Scheme
syntax enable
set background=light
set t_ut=
colorscheme solarized

" Plugins
let g:Powerline_symbols = 'fancy'
let g:ctrlp_open_multiple_files = 't'
let g:ctrlp_working_path_mode   = 0

" TMUX configuration
if exists('$TMUX')  " Support resizing in tmux
  set ttymouse=xterm2
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" Windconfig

" Disable output and VCS files
set wildignore+=*.o,*.out,*.obj,.git,*.rbc,*.rbo,*.class,.svn,*.gem

" Disable archive files
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz

" Ignore bundler and sass cache
set wildignore+=*/vendor/gems/*,*/vendor/cache/*,*/.bundle/*,*/.sass-cache/*

" Ignore rails temporary asset caches
set wildignore+=*/tmp/cache/assets/*/sprockets/*,*/tmp/cache/assets/*/sass/*

" Disable temp and backup files
set wildignore+=*.swp,*~,._*

let g:syntastic_javascript_checkers = ['eslint']
