export ZSH=$HOME/.oh-my-zsh

plugins=(git zsh-syntax-highlighting bundler brew gem)

source $ZSH/oh-my-zsh.sh

for file in ~/.{exports,aliases,functions,extra}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:$HOME/.bin"

# Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# nvm
export NVM_DIR="~/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# load pure prompt
fpath=("$HOME/.bin" $fpath)
autoload -U promptinit && promptinit
prompt pure
