export ZSH=$HOME/.oh-my-zsh

plugins=(git zsh-syntax-highlighting bundler brew gem)

source $ZSH/oh-my-zsh.sh

for file in ~/.{exports,aliases,functions,extra}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.bin"

# Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.pyenv/bin:$PATH"

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# nvm
if [ -f ~/.nvm/nvm.sh ]; then source ~/.nvm/nvm.sh; fi

# load pure prompt
fpath=("$HOME/.zfunctions" $fpath)
autoload -U promptinit && promptinit
prompt pure
